version: "3"

services:

  chat-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-service
    ports:
      - 8088:8080
      - 8889:8889
    environment:
      - JVM_ARGS=-Xmx200m
      - DEBUG_MODE=true #possible values: true, false, suspend
      - DEBUG_PORT=8889
